# Generated by Django 6.0.5 on 2026-05-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('salary', models.FloatField(max_length=30)),
                ('image', models.FileField(upload_to='')),
                ('description', models.CharField()),
                ('experience', models.CharField()),
                ('location', models.CharField(max_length=20)),
                ('skills', models.CharField(max_length=20)),
                ('creation_date', models.DateField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.recruiter')),
            ],
        ),
    ]
